#!/usr/bin/env bash

set -e
set -o pipefail

echo "+----------------------------+"
echo "| Executing tests using sbt  |"
echo "+----------------------------+"
sbt --warn ++$SEMAPHORE_SCALA_VERSION test 
